apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kvm-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.122.240-192.168.122.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kvm-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - kvm-pool

